### ISSUE TITLE
i got csrf token miss match

### ISSUE THREAD

**Issue by sayasuhendra** [filippetrovicAT/breeze-nuxt#1]
I can login normally. but when i post/submit a register form for a new user, i got this error 

![image](https://user-images.githubusercontent.com/4870292/154995896-49292fd1-4383-4ac4-9da1-6ef80c72a7e2.png)

**Comment by filippetrovicAT** [comment]
Fixed it. Thanks! 8afa50804b79955c8a6e70e8753c68446c15d2b6
